[project]
name = "pixi-tutorial"
version = "0.1.0"
description = "A quick pixi tutorial"
authors = ["Joseph Specht <jspecht3@illinois.edu>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
gen-data = { cmd = "python gen-data.py", cwd = "python-files" }
gen-plot = { cmd = "python plotting.py", depends-on = ["gen-data"], cwd = "python-files" }
open-plot = { cmd = "open trig.png", depends-on = ["gen-plot"], cwd = "python-files" }

[dependencies]
numpy = ">=2.0.1,<3"
matplotlib = ">=3.9.1,<4"
